---
spring:
  application:
    name: eureka-nynct1
  profiles: eureka-nynct1
server:
  port: 8761
eureka:
  server:
    enableSelfPreservation: false #是否开启自我保护模式，默认为true。
    renewalPercentThreshold: 0.65 #
  instance:
    preferIpAddress: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    metadataMap:
      user: ${security.user.name}
      password: ${security.user.password}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://nynct_service:NL_7KKWO8@eureka-nynct2:8762/eureka/
---
spring:
  application:
    name: eureka-nynct2
  profiles: eureka-nynct2
server:
  port: 8762
eureka:
  server:
    enableSelfPreservation: false #是否开启自我保护模式，默认为true。
    renewalPercentThreshold: 0.65 #
  instance:
    preferIpAddress: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    metadataMap:
      user: ${security.user.name}
      password: ${security.user.password}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://nynct_service:NL_7KKWO8@eureka-nynct1:8761/eureka/