version: '3.1'

services:
  eureka-server2:
    image: nynct.registry:9999/eureka-server:1.0.0-${NYNCT_PROFILE}
    restart: always
    hostname: eureka-server2
    ports:
      - 8762:8762
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts-out
      - ./logs:/logs
      - ./config:/config
    command:
      - /bin/sh
      - -c
      - |
        ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        echo Asia/Shanghai > /etc/timezone
        cat /etc/hosts-out>>/etc/hosts
        java -jar eureka-server.jar --spring.profiles.active=eureka-nynct2 --eureka.instance.ip-address=${SERVER_IP}