spring:
  application:
    name: config-server
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: file:./config-repo
        bootstrap: true
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 60
  client:
    serviceUrl:
      defaultZone: http://nynct_service:NL_7KKWO8@eureka-nynct1:8761/eureka/,http://nynct_service:NL_7KKWO8@eureka-nynct2:8762/eureka/
server:
  port: 8889
management:
  endpoints:
    web:
      exposure:
        include: '*'   #refresh